export const seedCaseManagers = [
  {
    userName: 'johndoe',
    firstName: 'John',
    lastName: 'Doe',
    phone: '8623817665',
    email: 'johndoe@cm.io',
  },
  {
    userName: 'cmangam0',
    firstName: 'Chane',
    lastName: 'Mangam',
    email: 'cmangam0@berkeley.edu',
    phone: '789-400-2469',
  },
  {
    userName: 'apaik1',
    firstName: 'Anneliese',
    lastName: 'Paik',
    email: 'apaik1@yellowbook.com',
    phone: '585-479-5214',
  },
  {
    userName: 'ibrattell2',
    firstName: 'Ivett',
    lastName: 'Brattell',
    email: 'ibrattell2@pinterest.com',
    phone: '658-570-0950',
  },
  {
    userName: 'mpashe3',
    firstName: 'Michale',
    lastName: 'Pashe',
    email: 'mpashe3@infoseek.co.jp',
    phone: '202-109-2830',
  },
  {
    userName: 'sadne4',
    firstName: 'Sibyl',
    lastName: 'Adne',
    email: 'sadne4@oracle.com',
    phone: '571-158-7226',
  },
  {
    userName: 'hantonopoulos5',
    firstName: 'Hamil',
    lastName: 'Antonopoulos',
    email: 'hantonopoulos5@gravatar.com',
    phone: '774-910-6785',
  },
  {
    userName: 'tcarrabot6',
    firstName: 'Tova',
    lastName: 'Carrabot',
    email: 'tcarrabot6@chronoengine.com',
    phone: '961-571-9996',
  },
  {
    userName: 'hkeppel7',
    firstName: 'Halli',
    lastName: 'Keppel',
    email: 'hkeppel7@chronoengine.com',
    phone: '527-461-9155',
  },
  {
    userName: 'vpugsley8',
    firstName: 'Von',
    lastName: 'Pugsley',
    email: 'vpugsley8@ehow.com',
    phone: '594-609-5897',
  },
  {
    userName: 'ccarver9',
    firstName: 'Corine',
    lastName: 'Carver',
    email: 'ccarver9@sohu.com',
    phone: '481-391-4197',
  },
  {
    userName: 'dreddihougha',
    firstName: 'Duke',
    lastName: 'Reddihough',
    email: 'dreddihougha@latimes.com',
    phone: '961-633-8610',
  },
  {
    userName: 'jdennistonb',
    firstName: 'Jeana',
    lastName: 'Denniston',
    email: 'jdennistonb@illinois.edu',
    phone: '480-307-3526',
  },
  {
    userName: 'mnashec',
    firstName: 'Milzie',
    lastName: 'Nashe',
    email: 'mnashec@dot.gov',
    phone: '887-535-9938',
  },
  {
    userName: 'aewbachd',
    firstName: 'Andree',
    lastName: 'Ewbach',
    email: 'aewbachd@discovery.com',
    phone: '600-644-3557',
  },
  {
    userName: 'vblankette',
    firstName: 'Vitoria',
    lastName: 'Blankett',
    email: 'vblankette@sphinn.com',
    phone: '992-439-6891',
  },
  {
    userName: 'agillfordf',
    firstName: 'Audrye',
    lastName: 'Gillford',
    email: 'agillfordf@ezinearticles.com',
    phone: '288-809-7411',
  },
  {
    userName: 'suppettg',
    firstName: 'Susann',
    lastName: 'Uppett',
    email: 'suppettg@devhub.com',
    phone: '496-233-7606',
  },
  {
    userName: 'cphareh',
    firstName: 'Carolyne',
    lastName: 'Phare',
    email: 'cphareh@omniture.com',
    phone: '865-705-1014',
  },
  {
    userName: 'mapplegatei',
    firstName: 'Matthaeus',
    lastName: 'Applegate',
    email: 'mapplegatei@gravatar.com',
    phone: '943-177-1645',
  },
];
