export const seedDoctors = [
  {
    firstName: 'Dacia',
    lastName: 'Estrella',
    email: 'destrella0@comcast.net',
    phone: '438-725-2540',
    profession: 'Wise Consumer Products',
  },
  {
    firstName: 'Dulci',
    lastName: 'Masden',
    email: 'dmasden1@elpais.com',
    phone: '710-774-6728',
    profession: 'REMEDYREPACK INC.',
  },
  {
    firstName: 'Cesya',
    lastName: 'Smyley',
    email: 'csmyley2@cafepress.com',
    phone: '836-702-8311',
    profession: 'Benco Dental Company',
  },
  {
    firstName: 'Meggie',
    lastName: 'Hutchins',
    email: 'mhutchins3@sbwire.com',
    phone: '735-905-7879',
    profession: 'Citron Pharma LLC',
  },
  {
    firstName: 'Lindsay',
    lastName: 'Rabbage',
    email: 'lrabbage4@w3.org',
    phone: '404-966-6970',
    profession: 'Antigen Laboratories, Inc.',
  },
  {
    firstName: 'Vitia',
    lastName: 'Cuolahan',
    email: 'vcuolahan5@youku.com',
    phone: '206-444-1687',
    profession: 'Rebel Distributors Corp',
  },
  {
    firstName: 'Ruggiero',
    lastName: 'Fulton',
    email: 'rfulton6@youtube.com',
    phone: '542-714-3431',
    profession: 'Roberts Oxygen Company, Inc.',
  },
  {
    firstName: 'Guglielmo',
    lastName: 'Klimowicz',
    email: 'gklimowicz7@domainmarket.com',
    phone: '841-510-4557',
    profession: 'RECEPTOPHARM INC',
  },
  {
    firstName: 'Annnora',
    lastName: 'Scase',
    email: 'ascase8@is.gd',
    phone: '403-867-9885',
    profession: 'The Kroger Co',
  },
  {
    firstName: 'Kial',
    lastName: 'McMearty',
    email: 'kmcmearty9@so-net.ne.jp',
    phone: '118-666-2645',
    profession: 'Accudial Pharmaceutical, Inc.',
  },
  {
    firstName: 'Ewart',
    lastName: 'Patron',
    email: 'epatrona@tripadvisor.com',
    phone: '905-231-8229',
    profession: 'Cardinal Health',
  },
  {
    firstName: 'Levon',
    lastName: 'Harriskine',
    email: 'lharriskineb@nymag.com',
    phone: '262-327-6943',
    profession: 'Red River Welding Supply Co. dba McGinnis Welding Supply Co',
  },
  {
    firstName: 'Lynda',
    lastName: 'Edelmann',
    email: 'ledelmannc@google.de',
    phone: '666-337-3623',
    profession: 'SKINFOOD CO., LTD.',
  },
  {
    firstName: 'Gigi',
    lastName: 'Wolstencroft',
    email: 'gwolstencroftd@163.com',
    phone: '333-453-9193',
    profession: 'Bayer HealthCare Pharmaceuticals Inc.',
  },
  {
    firstName: 'Nealon',
    lastName: 'Olfert',
    email: 'nolferte@yellowbook.com',
    phone: '840-832-2000',
    profession: 'Zenith Medicosm SL',
  },
  {
    firstName: 'Zollie',
    lastName: 'Trundell',
    email: 'ztrundellf@blinklist.com',
    phone: '746-895-6462',
    profession: 'ALK-Abello, Inc.',
  },
  {
    firstName: 'Carmel',
    lastName: 'Pennazzi',
    email: 'cpennazzig@quantcast.com',
    phone: '337-535-7294',
    profession: 'Energique, Inc.',
  },
  {
    firstName: 'Bailie',
    lastName: 'Dast',
    email: 'bdasth@google.fr',
    phone: '151-628-9887',
    profession: 'Hospira, Inc.',
  },
  {
    firstName: 'Friederike',
    lastName: 'Capaldo',
    email: 'fcapaldoi@mediafire.com',
    phone: '928-950-9160',
    profession: 'Clinical Solutions Wholesale',
  },
];
