export const seedPatients = [
  {
    firstName: 'Aveline',
    lastName: 'Kaine',
    email: 'akaine0@usnews.com',
    phone: '203-313-4014',
  },
  {
    firstName: 'Biddy',
    lastName: 'Martschik',
    email: 'bmartschik1@imdb.com',
    phone: '263-558-2597',
  },
  {
    firstName: 'Elisabet',
    lastName: 'Dupoy',
    email: 'edupoy2@liveinternet.ru',
    phone: '255-389-0575',
  },
  {
    firstName: 'Daisie',
    lastName: 'Leyes',
    email: 'dleyes3@nasa.gov',
    phone: '947-519-1529',
  },
  {
    firstName: 'Nathaniel',
    lastName: 'Marquot',
    email: 'nmarquot4@usda.gov',
    phone: '923-371-1258',
  },
  {
    firstName: 'Hart',
    lastName: 'Yakunchikov',
    email: 'hyakunchikov5@storify.com',
    phone: '856-146-0898',
  },
  {
    firstName: 'Jemmy',
    lastName: "O' Borne",
    email: 'joborne6@joomla.org',
    phone: '977-701-1188',
  },
  {
    firstName: 'Selma',
    lastName: 'Iashvili',
    email: 'siashvili7@pinterest.com',
    phone: '447-651-8696',
  },
  {
    firstName: 'Bernete',
    lastName: 'Skegg',
    email: 'bskegg8@adobe.com',
    phone: '674-273-9143',
  },
  {
    firstName: 'Andras',
    lastName: 'Garroch',
    email: 'agarroch9@vistaprint.com',
    phone: '380-738-3755',
  },
  {
    firstName: 'Dermot',
    lastName: 'Twede',
    email: 'dtwedea@ebay.com',
    phone: '754-860-2374',
  },
  {
    firstName: 'Sibley',
    lastName: 'McLagan',
    email: 'smclaganb@cnn.com',
    phone: '409-891-9060',
  },
  {
    firstName: 'Kacie',
    lastName: 'Sketcher',
    email: 'ksketcherc@cocolog-nifty.com',
    phone: '836-461-2050',
  },
  {
    firstName: 'Taite',
    lastName: 'Doget',
    email: 'tdogetd@twitpic.com',
    phone: '584-159-1117',
  },
  {
    firstName: 'Babbie',
    lastName: 'Hailston',
    email: 'bhailstone@so-net.ne.jp',
    phone: '331-600-5419',
  },
  {
    firstName: 'Ag',
    lastName: 'Lemarie',
    email: 'alemarief@zdnet.com',
    phone: '434-593-9442',
  },
  {
    firstName: 'Natka',
    lastName: 'Hainge',
    email: 'nhaingeg@de.vu',
    phone: '622-687-9442',
  },
  {
    firstName: 'Dun',
    lastName: 'Stopher',
    email: 'dstopherh@so-net.ne.jp',
    phone: '389-635-2798',
  },
  {
    firstName: 'Weidar',
    lastName: 'Bosquet',
    email: 'wbosqueti@cnet.com',
    phone: '247-467-4008',
  },
  {
    firstName: 'Walther',
    lastName: 'Tomei',
    email: 'wtomeij@mysql.com',
    phone: '280-587-3341',
  },
];
